---
- name: Create SystemD service file
  template:
      dest: /etc/systemd/system/bamboo.service
      src: bamboo.service.j2
      mode: 0744
  when:
    - bamboo_create_systemd

- name: Reload SystemD files
  systemd:
      name: bamboo
      daemon_reload: true
  when:
    - bamboo_create_systemd