---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos_7
    image: centos:7
    docker_file: Dockerfile.j2

  - name: centos_8
    image: centos:8
    docker_file: Dockerfile.j2

  - name: debian_10
    image: debian:10
    docker_file: Dockerfile.j2

  - name: ubuntu_1804
    image: ubuntu:18.04
    docker_file: Dockerfile.j2

  - name: ubuntu_2004
    image: ubuntu:20.04
    docker_file: Dockerfile.j2

provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
